#!/usr/bin/env python3
"""
build_web.py — PlatformIO pre-build script
1. Runs `npm install` (if node_modules missing) then `npm run build` inside web/
2. Reads web/dist/index.html
3. Generates src/web/WebContent.h as a PROGMEM C string so the ESP32
   WebServer can serve the Vue SPA without a filesystem partition.

Registered in platformio.ini:
    extra_scripts = pre:script/build_web.py
"""

import os
import subprocess
import sys

Import("env")  # noqa: F821 — PlatformIO injects this

PROJECT_DIR  = env.subst("$PROJECT_DIR")  # noqa: F821
WEB_DIR      = os.path.join(PROJECT_DIR, "web")
DIST_HTML    = os.path.join(WEB_DIR, "dist", "index.html")
CONTENT_H    = os.path.join(PROJECT_DIR, "src", "web", "WebContent.h")

def run(cmd, cwd):
    print(f"[build_web] $ {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=cwd, capture_output=False)
    if result.returncode != 0:
        print(f"[build_web] ❌ Command failed with exit code {result.returncode}")
        sys.exit(result.returncode)

def escape_c_string(html: str) -> str:
    """Escape a string for embedding in a C raw string literal (R"HTML(...)HTML")."""
    # The only sequence that can break R"HTML(...)HTML" is the string )HTML"
    # Replace it with a safe alternative (two adjacent raw string literals is
    # not available in C++, so we use \x29 for ')')
    return html.replace(')HTML"', r'\x29HTML"')

def main():
    # ── 1. Install npm dependencies if needed ───────────────────────────────
    nm = os.path.join(WEB_DIR, "node_modules")
    pkg = os.path.join(WEB_DIR, "package.json")
    if not os.path.exists(pkg):
        print(f"[build_web] ⚠️  {pkg} not found — skipping web build")
        return
    if not os.path.exists(nm):
        print("[build_web] Installing npm dependencies...")
        run(["npm", "install"], cwd=WEB_DIR)

    # ── 2. Build the Vue project ─────────────────────────────────────────────
    print("[build_web] Building Vue frontend...")
    run(["npm", "run", "build"], cwd=WEB_DIR)

    # ── 3. Read output HTML ──────────────────────────────────────────────────
    if not os.path.exists(DIST_HTML):
        print(f"[build_web] ❌ Build output not found: {DIST_HTML}")
        sys.exit(1)

    with open(DIST_HTML, encoding="utf-8") as f:
        html = f.read()

    size_kb = len(html.encode("utf-8")) / 1024
    print(f"[build_web] HTML size: {size_kb:.1f} KB")

    # ── 4. Generate WebContent.h ─────────────────────────────────────────────
    safe_html = escape_c_string(html)
    header = (
        "#pragma once\n"
        "// ============================================================\n"
        "// AUTO-GENERATED by script/build_web.py — DO NOT EDIT\n"
        f"// Source: web/dist/index.html  ({size_kb:.1f} KB)\n"
        "// ============================================================\n"
        "\n"
        "const char WEB_HTML[] PROGMEM = R\"HTML(\n"
        f"{safe_html}\n"
        ")HTML\";\n"
    )

    os.makedirs(os.path.dirname(CONTENT_H), exist_ok=True)
    with open(CONTENT_H, "w", encoding="utf-8") as f:
        f.write(header)

    print(f"[build_web] ✅ Generated {CONTENT_H}")

main()

