import {defineConfig} from 'vite'
import vue from '@vitejs/plugin-vue'
import {viteSingleFile} from 'vite-plugin-singlefile'
import {readFileSync, existsSync} from 'fs'
import {resolve} from 'path'

// Load ESP32 constants generated by script/pre_build.py
const esp32ConfigPath = resolve(__dirname, 'esp32_config.json')
let esp32Data = {};

if (existsSync(esp32ConfigPath)) {
  esp32Data = JSON.parse(readFileSync(esp32ConfigPath, 'utf-8'))
}

export default defineConfig({
  plugins: [
    vue(),
    viteSingleFile()          // inline all assets → one self-contained index.html
  ],
  define: {
    // Replaced at build time; injected into the HTML by App.vue / main.js
    __ESP32_DATA__: JSON.stringify(esp32Data)
  },
  build: {
    outDir: 'dist',
    assetsInlineLimit: Infinity,  // inline everything
    cssCodeSplit: false
  },
  css: {
    preprocessorOptions: {
      scss: {
        api: 'modern'
      }   // suppress legacy-js-api deprecation
    }
  }
})

